name: Versioning Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      frontend_changed: ${{ steps.filter.outputs.frontend_changed }}
      backend_changed: ${{ steps.filter.outputs.backend_changed }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -q '^app/'; then echo "frontend_changed=true" >> $GITHUB_OUTPUT; else echo "frontend_changed=false" >> $GITHUB_OUTPUT; fi
          if echo "$CHANGED_FILES" | grep -q '^backend/'; then echo "backend_changed=true" >> $GITHUB_OUTPUT; else echo "backend_changed=false" >> $GITHUB_OUTPUT; fi

  determine_increment:
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.frontend_changed == 'true' || needs.check_changes.outputs.backend_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Determinar tipo de incremento pelo Conventional Commit
        id: inc_type
        run: |
          COMMITS=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.sha }} --pretty=%s)
          TYPE="patch"
          while IFS= read -r line; do
            if [[ "$line" == *"BREAKING CHANGE"* ]] || [[ "$line" == *"!:"* ]]; then
              TYPE="major"
              break
            elif [[ "$line" == feat* ]]; then
              [[ "$TYPE" != "major" ]] && TYPE="minor"
            fi
          done <<< "$COMMITS"
          echo "TYPE=$TYPE" >> $GITHUB_ENV
          echo "Tipo de incremento detectado: $TYPE"

  increment_version:
    runs-on: ubuntu-latest
    needs: determine_increment
    if: needs.check_changes.outputs.frontend_changed == 'true' || needs.check_changes.outputs.backend_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Dar permissão ao script
        run: chmod +x ./scripts/increment-version.sh
      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Rodar versionamento
        run: |
          TARGET=""
          if [[ "${{ needs.check_changes.outputs.frontend_changed }}" == "true" && "${{ needs.check_changes.outputs.backend_changed }}" == "true" ]]; then
            TARGET="all"
          elif [[ "${{ needs.check_changes.outputs.frontend_changed }}" == "true" ]]; then
            TARGET="front"
          elif [[ "${{ needs.check_changes.outputs.backend_changed }}" == "true" ]]; then
            TARGET="back"
          fi
          ./scripts/increment-version.sh $TYPE $TARGET
